Repository kadirnar/whisper-plus, pull requests merged in 2023-11, with the labels that each got.

#1 🚀 Initial commit
  .pre-commit-config.yaml
  README.md
  dev-requirements.txt
  requirements.txt
  scripts/package.py
  setup.cfg
  setup.py
  whisperplus/__init__.py
Labels: enhancement

#5 🤖 Added Whisper model and applied optimizations.
  whisperplus/demo.py
  whisperplus/pipelines/whisper.py
  whisperplus/utils/__init__.py
  whisperplus/utils/download_utils.py
Labels: enhancement

#6 ✨ feat: Add YouTube Speech-to-text demo
  whisperplus/demo.py
  whisperplus/pipelines/whisper.py
  whisperplus/utils/download_utils.py
Labels: enhancement

#7 feat: 🤖 Added Hugging Face Model Deployment with Gradio for enhanced features!
  README.md
  doc/openai-whisper.jpg
  whisperplus/__init__.py
  whisperplus/app.py
  whisperplus/demo.py
Labels: documentation, enhancement

#9 Update WhisperPlus version and fix example URL
  README.md
  whisperplus/__init__.py
  whisperplus/app.py
Labels: documentation

#10 Update better downloader and audio convertion & summarization
  README.md
  requirements.txt
  whisperplus/__init__.py
  whisperplus/pipelines/summarization.py
  whisperplus/utils/download_utils.py
Labels: documentation, enhancement

#15 feat: 🚀 Add GitHub workflows for package testing and CI, integrate logger support in whisper.py 🤖
  .github/FUNDING.yml
  .github/workflows/ci.yml
  .github/workflows/package_testing.yml
  .github/workflows/publish_pypi.yml
  whisperplus/__init__.py
  whisperplus/pipelines/whisper.py
Labels: enhancement

#16 Update GitHub Actions workflows
  .github/workflows/ci.yml
  .github/workflows/package_testing.yml
  .github/workflows/publish_pypi.yml
Labels: enhancement

#17 Add Speaker Diarization Feature with Pyannote 🗣️
  README.md
  requirements.txt
  whisperplus/__init__.py
  whisperplus/pipelines/whisper_diarize.py
  whisperplus/utils/text_utils.py
Labels: documentation, enhancement

#19 Update requirements.txt and TypeError error has been fixed.
  requirements.txt
  whisperplus/__init__.py
  whisperplus/utils/text_utils.py
Labels: bug

#23 Update ASR model and add batch size and return
  README.md
  whisperplus/pipelines/whisper_diarize.py
Labels: documentation, enhancement

#25 Update CI workflow and package testing workflow
  .github/workflows/ci.yml
  .github/workflows/package_testing.yml
  requirements.txt
Labels: bug

#26 Add speaker diarization functionality
  whisperplus/app.py
Labels: enhancement
