Repository kadirnar/whisper-plus, pull requests merged in 2024-01, with the labels that each got.

#32 🤖 Update readme.md with RAG example
  README.md
  dev-requirements.txt
  whisperplus/__init__.py
Labels: documentation, enhancement

#36 Feature/rag function
  README.md
  whisperplus/pipelines/__init__.py
  whisperplus/pipelines/chatbot.py
Labels: bug, documentation, enhancement

#38 🤩 Update isort version and change package version
  .pre-commit-config.yaml
  whisperplus/__init__.py
Labels: bug

#39 🚑Update requirements and version number
  MANIFEST.in
  requirements.txt
  setup.py
  whisperplus/__init__.py
Labels: bug

#40 🆙Update requirements.txt and version number
  README.md
  requirements.txt
  setup.py
  whisperplus/__init__.py
Labels: enhancement

#41 🐛Update requirements.txt and MANIFEST.in
  MANIFEST.in
  dev-requirements.txt
  requirements.txt
Labels: bug

#42 🚀Add pre-commit package to requirements.txt
  requirements.txt
  whisperplus/__init__.py
Labels: bug

#43 Fix pre commit
  README.md
Labels: documentation

#44 Fix/database failissue
  README.md
  requirements.txt
  whisperplus/pipelines/chatbot.py
Labels: bug, documentation

#49 🌠 Update chatbot.py filename
  whisperplus/pipelines/lancedb_chatbot.py
Labels: enhancement

#50 🚀 Add Long Text Summarization Feature
  README.md
  whisperplus/__init__.py
  whisperplus/pipelines/long_text_summarization.py
Labels: documentation, duplicate, enhancement

#51 🤩 Add Text-to-Speech Pipeline
  README.md
  whisperplus/pipelines/text2speech.py
Labels: documentation, duplicate, enhancement

#52 📰 Update README.md file
  README.md
Labels: documentation, enhancement

#53 🆙 Update Version
  README.md
  whisperplus/__init__.py
Labels: documentation, enhancement

#54 🚀 Add AutoLLM library for improved RAG support
  README.md
  requirements.txt
  whisperplus/pipelines/autollm_chatbot.py
Labels: documentation, enhancement

#55 🚀 Add demo notebook file
  .gitignore
  README.md
  notebook/demo.ipynb
  setup.py
  whisperplus/pipelines/autollm_chatbot.py
Labels: documentation, enhancement

#56 🌠 Add AutoCaption Feature
  README.md
  whisperplus/pipelines/whisper.py
  whisperplus/pipelines/whisper_autocaption.py
Labels: documentation, enhancement
