Repository kadirnar/whisper-plus, pull requests merged in 2024-05, with the labels that each got.

#75 🌞 Add more parameter support for Whisper pipeline
  requirements.txt
  whisperplus/pipelines/whisper.py
Labels: enhancement

#77 🥇 Add hqq optimization algorithm
  README.md
  requirements.txt
  whisperplus/__init__.py
  whisperplus/pipelines/whisper.py
Labels: documentation, enhancement

#78 🏄‍♂️ Add test code and Runpod platform support
  README.md
  requirements.txt
  scripts/runpod.sh
  whisperplus/pipelines/whisper.py
  whisperplus/test.py
Labels: documentation, enhancement

#79 💬 Add new parameters for hqq optimization method
  scripts/runpod.sh
  whisperplus/pipelines/whisper.py
  whisperplus/test.py
Labels: enhancement

#84 Add optional parameter and wer metric code
  README.md
  whisperplus/__init__.py
  whisperplus/audio_eval.py
  whisperplus/pipelines/whisper.py
Labels: bug, documentation, enhancement

#85 Add Readme file for metric results
  benckmarks.md
  whisperplus/audio_eval.py
Labels: documentation, enhancement

#90 Speed up library installation.
  README.md
  requirements.txt
Labels: documentation, enhancement

#92 Add yt-dlp instead of pytube to download youtube video
  README.md
  requirements.txt
  whisperplus/__init__.py
  whisperplus/app.py
  whisperplus/test.py
  whisperplus/utils/download_utils.py
Labels: bug, documentation

#94 Add speaker_diarization.txt file
  README.md
  speaker_diarization.txt
Labels: documentation, enhancement

#95 change misleading title 'Speech to Text' -> 'Text to Speech'
  README.md
Labels: documentation

#97 Add Hqq + Compile + Flash Attention support
  whisperplus/pipelines/whisper.py
Labels: enhancement

#99 🌠 Add CLI support
  requirements.txt
  whisperplus/cli.py
Labels: documentation, enhancement

#102 💯 Add load_model file
  whisperplus/model/load_model.py
  whisperplus/pipelines/whisper.py
Labels: enhancement

#105 🍎 Add Mlx library
  .pre-commit-config.yaml
  README.md
  doc/benchmarks/whisper_benckmarks.md
  whisperplus/pipelines/mlx_whisper/__init__.py
  whisperplus/pipelines/mlx_whisper/assets/gpt2.tiktoken
  whisperplus/pipelines/mlx_whisper/assets/mel_filters.npz
  whisperplus/pipelines/mlx_whisper/assets/multilingual.tiktoken
  whisperplus/pipelines/mlx_whisper/audio.py
  whisperplus/pipelines/mlx_whisper/benchmark.py
  whisperplus/pipelines/mlx_whisper/convert.py
  whisperplus/pipelines/mlx_whisper/decoding.py
  whisperplus/pipelines/mlx_whisper/load_models.py
  whisperplus/pipelines/mlx_whisper/requirements.txt
  whisperplus/pipelines/mlx_whisper/timing.py
  whisperplus/pipelines/mlx_whisper/tokenizer.py
  whisperplus/pipelines/mlx_whisper/torch_whisper.py
  whisperplus/pipelines/mlx_whisper/transcribe.py
  whisperplus/pipelines/mlx_whisper/version.py
  whisperplus/pipelines/mlx_whisper/whisper.py
  whisperplus/pipelines/whisper.py
Labels: bug, enhancement

#109 🍏 Add Lightning Mlx code to readme file
  README.md
Labels: documentation
